import React from "react";
import "../styles/logos.css";
import "../styles/dashboard.css";
import LegacyTeamList from "./LegacyTeamList";
import SideMenu from "./SideMenu";

export default function Logos() {
  return (
    <div className="dashboard">
      <LegacyTeamList />
      <div className="logo-rapper">
        <h1>Slect A Team</h1>
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/NE/NE_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/MIA/MIA_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/BUF/BUF_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/NYJ/NYJ_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/BAL/BAL_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/PIT/PIT_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/CLE/CLE_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/CIN/CIN_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/HOU/HOU_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/IND/IND_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/TEN/TEN_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/JAX/JAX_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/KC/KC_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/LAC/LAC_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/DEN/DEN_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/OAK/OAK_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/DAL/DAL_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/PHI/PHI_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/WAS/WAS_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/NYG/NYG_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/CHI/CHI_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/MIN/MIN_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/GB/GB_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/DET/DET_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/NO/NO_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/ATL/ATL_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/CAR/CAR_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/TB/TB_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/LA/LA_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/SEA/SEA_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/SF/SF_logo-80x90.gif"
          alt="logo"
        />
        <img
          src="http://i.nflcdn.com/static/site/7.5/img/teams/ARZ/ARZ_logo-80x90.gif"
          alt="logo"
        />
      </div>
      <SideMenu />
    </div>
  );
}
